use_frameworks!

target 'BigFloat_Example' do
  pod 'BigFloat', :path => '../'
  pod 'BigInt', '~> 3.0'
  pod 'SipHash', '~>1.2'

  target 'BigFloat_Tests' do
    inherit! :search_paths

    
  end
end


